# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          yunii things
paginate:       5
baseurl:        "/"
url:            "https://yuniithings.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         JongYun
  url:          https://yuniithings.github.io
  email:        yunii1204@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
